#coding : UTF-8
UT_ShowMessage(u"きゃー，はずかしいわん")
UT_Sleep(3)
UT_CaptureScreen(u"test1.png")
UT_ShowWindow(False)
UT_Sleep(3)
UT_ShowWindow(True)
UT_ShowMessage(u"ぶひー")
UT_CaptureScreen(u"test2.png")
UT_Terminate()
